### ISSUE TITLE
Great job using issues

### ISSUE THREAD

**Issue by Chebotarev** [ragegage/robinbanks#54]
I noticed it seems like you are using issues to keep track of your project goals, which is awesome! I'll try not to get in your way too much, so I'll just add a few notes as comments under this issue.

**Comment by Chebotarev** [comment]
I see you're thinking about using Rickshaw for graphing some of your data. I would also check out some of the features of D3 for React: http://www.reactd3.org/. I think either one will work for you, just check out which feature set is better.

**Comment by Chebotarev** [comment]
I think your `stock_list_item` linked list idea is interesting, let me know if you have any trouble implementing it. In your db schema, you probably want `stock_id` and `next_stock_list_id` to both be integers. Additionally, you should probably allow `next_stock_list_id` to be null, to indicate the end of the list.

**Comment by ragegage** [comment]
Thanks for noticing that-- I don't know why I said next_stock_list_id would be a datetime!
